version: "3.9"
services:
  app:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html:ro
    expose:
      - 80
    environment:
      VIRTUAL_HOST: uswt.tobiass.nl
      LETSENCRYPT_HOST: uswt.tobiass.nl
    networks:
      - proxy

networks:
  proxy:
    external: true
